title: "ProfPlan"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md
  - UserGuideTest.html

markdown: kramdown

repository: "AY2324S1-CS2103T-W15-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
